#Requires -Version 7.0
<#
.SYNOPSIS
  Installs the legacy support app on all participant VMs via Custom Script Extension.

.DESCRIPTION
  Run this script after participants complete Module 3 (VM deployed). It iterates
  over all slots and applies the 'InstallLegacyApp' Custom Script Extension to each
  VM, injecting the slot ID, ingestion endpoint, and per-slot ingestion key. Slots
  where the VM doesn't exist are skipped with a warning.

  The extension runs asynchronously on each VM. After the script completes, participants
  can verify installation via their VM blade > Extensions + applications.

.PARAMETER SubscriptionId
  Azure subscription ID where the spoke resource groups live.

.PARAMETER IngestionEndpoint
  Base URL of the shared Ingestion API, e.g. https://workshop-ingest-XXXX.azurewebsites.net

.PARAMETER AppBinaryUrl
  HTTPS URL to the legacy-system single-file .NET executable.
  Example: https://github.com/<org>/<repo>/releases/download/v1.0/legacy-system.exe

.PARAMETER InstallScriptUrl
  HTTPS URL to the PowerShell install script (install.ps1 in app/legacy-system/install/).
  Example: https://raw.githubusercontent.com/<org>/<repo>/main/app/legacy-system/install/install.ps1
.PARAMETER ScenarioUrl
  Optional HTTPS URL to a custom scenario.json override.
  If omitted the scenario.json bundled with the published exe is used.
  Example: https://raw.githubusercontent.com/<org>/<repo>/main/app/legacy-system/scenario.json
.PARAMETER IngestionKeysJson
  JSON object mapping slot -> key, e.g. '{"user01":"key1","user02":"key2",...}'.
  Generated by seed-cohort.ps1 and written to infra/cohort-keys.json (gitignored).
  If not supplied, a shared fallback key from $Env:WORKSHOP_INGESTION_KEY is used.

.PARAMETER SlotCount
  Number of participant slots (default 30).

.PARAMETER Location
  Azure region (default eastus2).

.EXAMPLE
  $keys = Get-Content infra/cohort-keys.json | ConvertFrom-Json | ConvertTo-Json -Compress
  .\infra\install-legacy-app.ps1 `
    -SubscriptionId 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' `
    -IngestionEndpoint 'https://workshop-ingest-XXXX.azurewebsites.net' `
    -AppBinaryUrl 'https://github.com/org/repo/releases/download/v1.0/legacy-system.exe' `
    -InstallScriptUrl 'https://raw.githubusercontent.com/org/repo/main/app/legacy-system/install/install.ps1' `
    -IngestionKeysJson $keys
#>
[CmdletBinding(SupportsShouldProcess)]
param (
    [Parameter(Mandatory)][string]$SubscriptionId,
    [Parameter(Mandatory)][string]$IngestionEndpoint,
    [Parameter(Mandatory)][string]$AppBinaryUrl,
    [Parameter(Mandatory)][string]$InstallScriptUrl,
    [string]$IngestionKeysJson   = '',
    [string]$ScenarioUrl         = '',   # optional: custom scenario.json URL
    [int]   $SlotCount           = 30,
    [string]$Location            = 'eastus2'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Parse per-slot ingestion keys ──────────────────────────────────────────────
$keysMap = @{}
if ($IngestionKeysJson) {
    $parsed = $IngestionKeysJson | ConvertFrom-Json -AsHashtable
    foreach ($k in $parsed.Keys) { $keysMap[$k] = $parsed[$k] }
}
$fallbackKey = $Env:WORKSHOP_INGESTION_KEY

# ── Select subscription ────────────────────────────────────────────────────────
az account set --subscription $SubscriptionId
if ($LASTEXITCODE -ne 0) { throw "Failed to set subscription $SubscriptionId" }
Write-Host "Subscription: $SubscriptionId" -ForegroundColor Cyan

# ── Generate slot list ─────────────────────────────────────────────────────────
$slots = 1..$SlotCount | ForEach-Object { 'user{0:D2}' -f $_ }

$results = @{ succeeded = 0; skipped = 0; failed = 0 }

foreach ($slot in $slots) {
    $rg   = "$slot-rg"
    $vm   = "vm-$slot"

    # Resolve ingestion key for this slot
    $key = if ($keysMap.ContainsKey($slot)) { $keysMap[$slot] }
           elseif ($fallbackKey)            { $fallbackKey }
           else                             { '' }

    if (-not $key) {
        Write-Warning "[$slot] No ingestion key found — skipping"
        $results.skipped++
        continue
    }

    # Check VM exists
    $vmId = az vm show --resource-group $rg --name $vm --query id --output tsv 2>$null
    if ($LASTEXITCODE -ne 0 -or -not $vmId) {
        Write-Warning "[$slot] VM '$vm' not found in '$rg' — skipping (participant may not have completed Module 3 yet)"
        $results.skipped++
        continue
    }

    Write-Host "[$slot] Installing legacy app on $vm ..." -ForegroundColor Yellow

    # Build the protected settings JSON (contains the secret key)
    $command = "powershell -ExecutionPolicy Unrestricted -File install.ps1 -SlotId '$slot' -IngestionEndpoint '$IngestionEndpoint' -IngestionKey '$key'"
    $protectedSettings = @{
        commandToExecute = $command
    } | ConvertTo-Json -Compress

    $settings = @{
        fileUris = @($InstallScriptUrl, $AppBinaryUrl)
    } | ConvertTo-Json -Compress

    # Append scenario.json URL if provided
    if ($ScenarioUrl) {
        $uriList = @($InstallScriptUrl, $AppBinaryUrl, $ScenarioUrl)
        $settings = @{ fileUris = $uriList } | ConvertTo-Json -Compress
    }

    if ($PSCmdlet.ShouldProcess("$vm in $rg", 'Apply CustomScriptExtension')) {
        az vm extension set `
            --resource-group $rg `
            --vm-name $vm `
            --name 'CustomScriptExtension' `
            --publisher 'Microsoft.Compute' `
            --version '1.10' `
            --settings $settings `
            --protected-settings $protectedSettings `
            --no-wait  # run async; check status via Extensions blade

        if ($LASTEXITCODE -ne 0) {
            Write-Error "[$slot] Extension set failed — check az CLI output above"
            $results.failed++
        } else {
            Write-Host "[$slot] Extension queued ✓" -ForegroundColor Green
            $results.succeeded++
        }
    }
}

# ── Summary ───────────────────────────────────────────────────────────────────
Write-Host ''
Write-Host '──────────────────────────────────────────' -ForegroundColor Cyan
Write-Host "Install complete.  succeeded=$($results.succeeded)  skipped=$($results.skipped)  failed=$($results.failed)" -ForegroundColor Cyan
Write-Host '──────────────────────────────────────────' -ForegroundColor Cyan
Write-Host ''
Write-Host 'Extensions run asynchronously. Ask participants to verify via:' -ForegroundColor White
Write-Host '  VM blade > Settings > Extensions + applications > InstallLegacyApp' -ForegroundColor White
Write-Host 'Status should reach "Provisioning succeeded" within ~2 minutes.' -ForegroundColor White

if ($results.failed -gt 0) {
    Write-Warning "$($results.failed) slot(s) failed. Re-run for specific slots by adjusting -SlotCount or filtering manually."
    exit 1
}
