'use strict';
// auth.js — Resolves participant slot from the x-team-key header.
//
// INGEST_KEYS_JSON app setting format: {"user01":"key1","user02":"key2",...}
// Generated by infra/seed-cohort.ps1 and written to the app setting via az CLI.
// The map is inverted at load time (key → slotId) for O(1) per-request lookups.

let _keyToSlot = null;

function getKeyToSlotMap() {
  if (_keyToSlot) return _keyToSlot;
  const raw = process.env.INGEST_KEYS_JSON || '{}';
  try {
    const slotToKey = JSON.parse(raw);
    _keyToSlot = {};
    for (const [slot, key] of Object.entries(slotToKey)) {
      _keyToSlot[String(key).trim()] = String(slot).trim();
    }
  } catch {
    _keyToSlot = {};
  }
  return _keyToSlot;
}

/**
 * Resolves the participant slotId from the x-team-key request header.
 * Returns the slotId string (e.g. 'user01') or null if the key is missing/invalid.
 */
function resolveSlot(headers) {
  const provided = (headers.get('x-team-key') || headers['x-team-key'] || '').trim();
  if (!provided) return null;
  return getKeyToSlotMap()[provided] || null;
}

module.exports = { resolveSlot };
